version: '3.9'

services:
  
  foundry:
     image: felddy/foundryvtt:release
     hostname: my_foundry_host      # change
     network_mode: host             # i found it faster, but cant specify ports now (will solve with nginx as reverseproxy)
     init: true
     restart: "unless-stopped"
     volumes:
       - type: bind
         source: ~/share/foundrydata
         target: /data
     environment:
       - FOUNDRY_PASSWORD=          # change
       - FOUNDRY_USERNAME=          # change
       - FOUNDRY_ADMIN_KEY=         # change